{% set name = "pybacktrack" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8b540d2839062ba4964b6635177e376b649ba360720040f1b519afd7f0cab1d3

build:
  noarch: python
  script_env:
    # There's no '.git' directory in source tarball, so explicitly provide version for setuptools_scm.
    - SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYBACKTRACK={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --ignore-installed
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    # Same setuptools* versions as in pyproject.toml (in source tarball).
    - setuptools >=61.0
    - setuptools_scm >=8.0  # Need this to process SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYBACKTRACK env var.
  run:
    - python >={{ python_min }}
    - gmt >=5.0
    - numpy
    - pygplates
    - scipy
    - packaging >=20.0

test:
  source_files:
    - tests
  imports:
    - pybacktrack
  requires:
    - python {{ python_min }}
    - pytest
  commands:
    - pytest

about:
  home: https://github.com/EarthByte/pyBacktrack
  summary: A tool for reconstructing paleobathymetry on oceanic and continental crust.
  dev_url: https://github.com/EarthByte/pyBacktrack
  doc_url: https://pybacktrack.readthedocs.io
  license: GPL-2.0-only
  license_family: GPL2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jcannon-gplates
